# Generated by Django 3.2.9 on 2021-12-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_genre'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='stories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.story'),
            preserve_default=False,
        ),
    ]
